export const postTypeMap = {
	post: 'posts',
	page: 'pages'
};

export const taxonomyMap = {
	tag: {
		endpoint: 'tags',
		queryVar: 'tag'
	},
	format: {
		endpoint: 'formats',
		queryVar: 'post_format'
	},
	category: {
		endpoint: 'categories',
		queryVar: 'category_name'
	}
};

export const GET_SESSION = 'GET_SESSION';
export const GET_SESSION_REQUEST = 'GET_SESSION_REQUEST';
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';
export const GET_SESSION_FAILURE = 'GET_SESSION_FAILURE';
export const GET_INFO = 'GET_INFO';
export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAILURE = 'GET_INFO_FAILURE';
export const GET_SINGULAR = 'GET_SINGULAR';
export const GET_SINGULAR_REQUEST = 'GET_SINGULAR_REQUEST';
export const GET_SINGULAR_SUCCESS = 'GET_SINGULAR_SUCCESS';
export const GET_SINGULAR_FAILURE = 'GET_SINGULAR_FAILURE';
export const GET_ARCHIVE = 'GET_ARCHIVE';
export const GET_ARCHIVE_REQUEST = 'GET_ARCHIVE_REQUEST';
export const GET_ARCHIVE_SUCCESS = 'GET_ARCHIVE_SUCCESS';
export const GET_ARCHIVE_FAILURE = 'GET_ARCHIVE_FAILURE';
export const GET_ARCHIVE_TERM = 'GET_ARCHIVE_TERM';
export const GET_ARCHIVE_TERM_REQUEST = 'GET_ARCHIVE_TERM_REQUEST';
export const GET_ARCHIVE_TERM_SUCCESS = 'GET_ARCHIVE_TERM_SUCCESS';
export const GET_ARCHIVE_TERM_FAILURE = 'GET_ARCHIVE_TERM_FAILURE';
export const GET_MENU = 'GET_MENU';
export const GET_MENU_REQUEST = 'GET_MENU_REQUEST';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';
export const UI_TOGGLE_SIDEBAR = 'UI_TOGGLE_SIDEBAR';
export const GET_TAXONOMIES = 'GET_TAXONOMIES';
export const GET_TAXONOMIES_REQUEST = 'GET_TAXONOMIES_REQUEST';
export const GET_TAXONOMIES_SUCCESS = 'GET_TAXONOMIES_SUCCESS';
export const GET_TAXONOMIES_FAILURE = 'GET_TAXONOMIES_FAILURE';
export const GET_TERMS = 'GET_TERMS';
export const GET_TERMS_REQUEST = 'GET_TERMS_REQUEST';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_FAILURE = 'GET_TERMS_FAILURE';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';
export const GALLERY_ADD = 'GALLERY_ADD';
export const GALLERY_RESET = 'GALLERY_RESET';
export const GALLERY_OPEN = 'GALLERY_OPEN';
export const GALLERY_CLOSE = 'GALLERY_CLOSE';
